export const FETCH_CATEGORY_LIST_INIT = "FETCH_CATEGORY_LIST_INIT";
export const FETCH_CATEGORY_LIST_PENDING = "FETCH_CATEGORY_LIST_PENDING";
export const FETCH_CATEGORY_LIST_SUCCESS = "FETCH_CATEGORY_LIST_SUCCESS";
export const FETCH_CATEGORY_LIST_FAILED = "FETCH_CATEGORY_LIST_FAILED";
