export const CHECK_USER_SESSION = "CHECK_USER_SESSION";
export const STOP_INITIAL_CHECK = "STOP_INITIAL_CHECK";
export const START_AUTHENTICATION = "START_AUTHENTICATION";

export const GOOGLE_SIGN_IN_INIT = "GOOGLE_SIGN_IN_INIT";
export const EMAIL_SIGN_IN_INIT = "EMAIL_SIGN_IN_INIT";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";

export const SIGN_UP_INIT = "SIGN_UP_INIT";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";
export const SIGN_UP_RESET = "SIGN_UP_RESET";

export const SIGN_OUT_INIT = "SIGN_OUT_INIT";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED";
